apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgsql-pv
  labels:
    app: keycloak
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/pgsql/data"
